version: '3'
services:
    tomcat:
        container_name: cantharella-web
        build: ./cantharella-web
        image: acheype/cantharella-web
        ports:
            - "80:8080"
        links:
            - "postgres"

    postgres:
        container_name: cantharella-db
        build: ./cantharella-db
        image: acheype/cantharella-db
        volumes:
            - /data/postgresql:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            # password of the user cantharella, only useful for db creation (if no data in /data/postgresql)
            - CANTHARELLA_PASSWORD=ctrl4